(ns wyssacademy.visual-synthesis.components.table
  (:require [wyssacademy.visual-synthesis.utils :as wvu]))

(def styles-comp
  {:thead {:comp :thead
           :class ["bg-gray-50" "xl:grid"]}
   :th {:comp :th
        :class ["px-6" "py-2" "text-sm" "text-gray-800"]}
   :td {:comp :td
        :class ["px-6" "py-4" "text-md" "text-gray-800"]}
   :tr {:comp :tr
        :class ["whitespace-nowrap"]}})

(declare thead)
(declare th)
(declare td)
(declare tr)

;; Autogenerated from styles-comp
(wyssacademy.visual-synthesis.utils/styles->components-litteral
 {:thead {:comp :thead, :class ["bg-gray-50"]},
  :th {:comp :th, :class ["px-6" "py-2" "text-sm" "text-gray-800"]},
  :td {:comp :td, :class ["px-6" "py-4" "text-md" "text-gray-800"]},
  :tr {:comp :tr, :class ["whitespace-nowrap"]}})

(defn container [& children]
  [:div {:class "flex flex-col my-8"}
   [:div {:class "py-2 -my-2 overflow-x-auto sm:mx-6 sm:px-6 lg:-mx-8 lg:px-8"}
    (into [:div
           {:class
            "inline-block min-w-full overflow-hidden align-middle border-b border-gray-200 shadow sm:rounded-lg"}]
          children)]])

(comment
  (th {:class ["py-5"]} [:div 5] [:strong 6])
  (thead {:class ["py-5"]} [:div 5] [:strong 6])
  )
